Add capacity_provider_strategy options to Service
reproio/ecs_deploy pull request #74
Opened 2022-03-14 16:33 UTC by joker1007

capacity_provider_strategy を 認識してservice作成時に反映できる様にする。

2022-03-17 02:53 UTC, okkez reviewed
変更自体は :ok: ですが、README.md も更新した方がよさそうです。

一度サービスを作成すると ecs_deploy 経由だと capacity provider strategy を変更できないのは意図的でしょうか？
そうであれば README.md に書いておいた方がよさそうです。

AWS CLI だと以下のようなコマンドを実行すると capacity provider strategy だけ変更できます。
```console
aws ecs update-service --cluster cluster-name --service service-name \
  --force-new-deployment \
  --capacity-provider-strategy capacityProvider=capacity-provider,weight=100,base=0 capacityProvider=capacity-provider2,weight=100,base=0
```

2022-03-17 08:14 UTC, joker1007 commented
これ、昔はあんまり変更できなかった名残りですね。
今のサポートレベルに合わせて対応できる様についでに修正ですね。

2022-03-18 00:56 UTC, okkez requested changes
以下のエラーメッセージの通り launch type から capacity provider strategy に変えるときと capacity provider strategy の内容を変えるときは `force_new_deployment: true` を追加する必要があります。

```console
Aws::ECS::Errors::InvalidParameterException: When switching from launch type to capacity provider strategy on an existing service, or making a change to a capacity provider strategy on a service that is already using one, you must force a new deployment.
```

以下のようなパッチをあてると動きました。

```diff
diff --git a/lib/ecs_deploy/service.rb b/lib/ecs_deploy/service.rb
index 0160215..59bb19c 100644
--- a/lib/ecs_deploy/service.rb
+++ b/lib/ecs_deploy/service.rb
@@ -109,6 +109,7 @@ module EcsDeploy

         service_options.merge!({service: @service_name})
         service_options.merge!({desired_count: @desired_count}) if @desired_count
+        service_options.merge!({force_new_deployment: true}) if need_force_new_deployment?(res.services)
         update_tags(@service_name, @tags)
         @response = @client.update_service(service_options)
         EcsDeploy.logger.info "update service [#{@service_name}] [#{@cluster}] [#{@region}] [#{Paint['OK', :green]}]"
@@ -175,5 +176,11 @@ module EcsDeploy
       suffix = @revision ? ":#{@revision}" : ""
       "#{@task_definition_name}#{suffix}"
     end
+
+    def need_force_new_deployment?(services)
+      current_service = services.detect { |s| s.service_name == @service_name }
+      (current_service.launch_type && @capacity_provider_strategy) ||
+        (current_service.capacity_provider_strategy != @capacity_provider_strategy)
+    end
   end
 end
```

2022-03-18 05:40 UTC, joker1007 commented
なるほど。

2022-03-22 04:30 UTC, okkez approved these changes

2022-03-23 08:13 UTC, joker1007 commented
用途上実害が無いから、force_new_deploymentの判定を簡易化して書いたんだけど、やっぱ気持ち悪いかな。
okkezさんのsuggestを採用するか。

2022-03-24 01:06 UTC, okkez requested changes
`need_force_deployment?` の判定がおかしいと思うので修正お願いします。

あと `force_new_deployment` の値をログに出力しておくと便利かなと思います。

2022-03-24 01:06 UTC, okkez commented on lib/ecs_deploy/service.rb
> +    end
これだと全部の capacity provider が同じ場合に `true` を返してしまうのと `@capacity_provider_strategy` の増減があった場合に正しく判定できないので以下のようにするのはどうでしょうか？

```suggestion
    private def need_force_new_deployment?(service)
      return false unless @capacity_provider_strategy

      current_strategies = service.capacity_provider_strategy
      return true if @capacity_provider_strategy.size != current_strategies.size

      !@capacity_provider_strategy.all? do |strategy|
        current_strategies.find do |current_strategy|
          strategy[:capacity_provider] == current_strategy.capacity_provider &&
            strategy[:weight] == current_strategy.weight &&
            strategy[:base] == current_strategy.base
        end
      end
    end
```

2022-03-25 08:31 UTC, joker1007 commented on lib/ecs_deploy/service.rb
> +    end
概ねその様に修正しました。

2022-03-25 08:54 UTC, okkez approved these changes
LGTM

2022-04-26 09:19 UTC, merged