Add runtime_platform to task_definition.
reproio/ecs_deploy pull request #92
Opened 2023-06-15 11:20 UTC by sugi

Add `runtime_platform` keyword to the task definition.
It allows users to use Graviton2 on Fargate like the following;

```ruby
 runtime_platform: { cpu_architecture: 'ARM64' },
````

2023-06-16 05:30 UTC, okkez requested changes

2023-06-16 05:30 UTC, okkez commented on .ruby-version
Please remove this file.

2023-06-16 05:57 UTC, sugi commented on .ruby-version
Ouch...
I'm sorry for the unintended.
I removed it and made a force push.

2023-06-19 04:32 UTC, okkez approved these changes
LTGM

2023-06-20 02:56 UTC, merged